export const MSG_CONST = <const>{
    ADDED: "Successfully Added.",
    ADD_FAILED: "Adding Failed On Save.",
    CLOSE: "Make Sure You Want To Close This.",
    CLOSE_FAILED: "Closing Failed On Save.",
    CLOSED: "Successfully Closed.",
    CHANGE_STATUS: "Make Sure You Want To Change This Status.",
    CHANGE_STATUS_FAILED: "Changing Status Failed On Save.",
    CHANGED_STATUS: "Status Successfully Changed.",
    CHANGE_PASSWORD: "Make Sure You Want To Change Password.",
    CHANGE_PASSWORD_FAILED: "Changing Password Failed On Save.",
    CHANGED_PASSWORD: "Password Successfully Changed.",
    CONFIRM_PASSWORD: "New Password And Confirm Password Does Not Match.",
    COPIED: "Copied To Clipboard",
    DATA_NOT_FOUND: "Data Not Found.",
    DELETE: 'Make Sure You Want To Delete This.',
    DELETE_FAILED: "Deleting Failed On Save.",
    DELETED: "Successfully Deleted.",
    FILE_UNSELECTED: "Please Select A File.",
    INVALID_FILE_TYPE: "Invalid File Type.",
    INVALID_FILE_SIZE: "File Size Is Too Big.",
    INVALID_SEARCH: "Please Complete At Least One Field.",
    INVALID_OTP: "Invalid OTP Entered.",
    LOGGED_IN: "Welcome To The System.",
    LOGGED_OUT: "You Have Been Logged Out.",
    LOGIN_FAILED: "Your Username And/Or Password Do Not Match.",
    LOCK: "Make Sure You Want To Lock This.",
    LOCK_FAILED: "Locking Failed On Save.",
    LOCKED: "Successfully Locked.",
    NO_DATA: "No Data.",
    NO_DATA_SELECTED: "No Data Selected.",
    UPLOADED: "Successfully Uploaded.",
    UPLOAD_FAILED: "Uploading Failed On Save.",
    UPDATE: "Make Sure You Want To Update This.",
    UPDATE_FAILED: "Updating Failed On Save.",
    UPDATED: "Successfully Updated.",
    REMOVE: "Make Sure You Want To Remove This.",
    REMOVE_FAILED: "Removing Failed On Save.",
    REMOVED: "Successfully Removed.",
    RESET_MSG: "Make Sure You Want To Reset This.",
    RESET_FAILED: "Reseting Failed On Save.",
    RESET: "Successfully Reset.",
    REQUIRED_FIELDS: "Please Complete All Required Fields.",
    SYSTEM_ERROR: "An Error Occurred While Connecting To The Server.",
    UNAUTHORIZED: "You Are Not Authorized To View This Page.",
    UNKNOWN_ERROR: "An Error Occurred While Processing Your Request.",
  }
  
  export const TITLE_CONST = <const>{
    CHANGE_PASSWORD: "Change Password?",
    CHANGE_STATUS: "Change Status?",
    CLOSE: "Close?",
    DELETE: "Delete?",
    ERROR: "Oh No!",
    INVALID: "Invalid!",
    LOGIN_FAILED: "Login Failed!",
    LOCK: "Lock?",
    UNAUTHORIZED: "Unauthorized!",
    RESET: "Reset?",
    REMOVE: "Remove?",
    SUCCESS: "Well Done!",
    UPDATE: "Update?",
    WARNING: "Warning!",
  }